<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_username</name>
   <tag></tag>
   <elementGuidId>ed6488e8-1841-4ddc-8325-a3ae8c4a77c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stripes-91301898</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stripes-91301898']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b4fbb3-e611-4bb6-acde-cd9ab393ed39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>bf8201fd-f8f3-48bc-a78a-ecf5d6295350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stripes-91301898</value>
      <webElementGuid>711ecae9-29e7-419b-ad60-1835d8705f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47d09f65-20ca-4206-bdb9-61759b33002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stripes-91301898&quot;)</value>
      <webElementGuid>eafc5e51-ce94-49ba-9614-8bd652155fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stripes-91301898']</value>
      <webElementGuid>f7727b13-c0c2-4ac9-b836-b6d7a494f5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>49e85995-4175-4d02-a812-be15691169df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>1d3eb2b7-7b34-41fa-963d-6fb14df3c99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'stripes-91301898' and @type = 'text']</value>
      <webElementGuid>8ec7c6fc-9d9c-4293-a08c-f4277a511eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
