<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_account.lastName</name>
   <tag></tag>
   <elementGuidId>c199aa3d-03b2-433e-88ec-54ec1d0ab8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;account.lastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='account.lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96fe2f31-1be7-43e4-b87a-707ad23547de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.lastName</value>
      <webElementGuid>40a6127f-43d8-406c-a3e7-7dad71e3d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>042cea5f-003b-4196-8d37-22bd1ab8bd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[2]/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>6b48c3ae-d782-4d9d-a142-caa12a4f8433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='account.lastName']</value>
      <webElementGuid>583590b0-53eb-4f1d-9bb5-02501e63b26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[2]/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>d18f835f-f9ff-4b1d-bc5c-e76193a0419d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>16db9578-af29-4d70-b4d0-dc082104e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'account.lastName' and @type = 'text']</value>
      <webElementGuid>cbab42c8-08e7-49b6-a055-9f3993c99a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
